repos:
  - repo: https://github.com/astral-sh/ruff
    rev: v0.0.249 # Change to the latest stable version
    hooks:
      - id: ruff
        name: ruff (linting)
        files: \.py$
        args: ["--select", "E", "W", "F", "C"]
