version: '3.9'

services:
  backend:
    build: ./backend
    ports:
      - "8000:10000"  # Map FastAPI internal port 10000 to host port 8000
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
