[tool.ruff]
# Ruff Linter and Formatter Configuration
line-length = 100
exclude = ["__pycache__", ".tox", ".venv", "tests/data"]
select = ["E", "W", "F", "C"]

[tool.mypy]
# Mypy Type Checker Configuration
python_version = "3.12"
ignore_missing_imports = true
disallow_untyped_defs = true

[tool.black]
# Black Code Formatter Configuration (Optional)
line-length = 100
target-version = ["py312"]

[tool.isort]
# Isort Configuration (Optional)
profile = "black"
known_third_party = ["fastapi", "uvicorn"]
